### PR TITLE
bash completion

### PR DESCRIPTION
**Pull request by hseg**
Found it convenient to have some tab-completion, thought I'd share.

### CODE REVIEW

**Comment by hseg** [comment]
As in #24, rebased -- in particular adding support for `pizauth status`

**Comment by ltratt** [comment]
Can you rebase this against master and force push please? Thanks!

**Comment by hseg** [comment]
On Wed, Dec 27, 2023 at 12:11:04AM -0800, Laurence Tratt wrote:
> Can you rebase this against master and force push please? Thanks!

Done!

**Comment by ltratt** [comment]
The bash completion file seems to have disappeared?

**Comment by hseg** [comment]
Oops, rebased too quickly and lost the commit. Should be fixed now.

**Comment by ltratt** [comment]
Thanks!

**Pull request merged**
