### PR TITLE
Allow HTTP and HTTP servers to be turned off

### PR DESCRIPTION
**Pull request by ltratt**
The main commit here is https://github.com/ltratt/pizauth/commit/e4ed00aafc9100075101dd4e8ec9d98649846a84, which allows one to set e.g. `http_listen = off` globally to ensure that only the HTTPS server is running. Both HTTP and HTTPS servers default to on.

@trembel Might you be able to test this and see if it works correctly in your setup?

### CODE REVIEW

**Comment by trembel** [comment]
Not sure if I'm doing something wrong.
I added
```
http_listen = "off";
https_listen = "off";
```
to my config. However, no error is shown on `pizauth server`, and `pizauth status` shows
```
ERROR pizauth authenticator not running or not responding
```
The same appears if one of `http_listen` or `https_listen` is set to off. With none of them in my configs, it works as before.

**Comment by ltratt** [comment]
`off` should be without quotes (to differentiate it from a hostname of "off").

**Comment by trembel** [comment]
Just tested, works for me.

However I feel its a bit missleading to be without quotes, as everything else is with quotes, but I don't see a better solution either.

**Comment by trembel** [comment]
What about using `None`? It is very broadly known as 'not being a string' (be it Rust or Python)

**Comment by ltratt** [comment]
> What about using None? 

Good idea! Fixed in https://github.com/ltratt/pizauth/pull/43/commits/925b5a1d741885ce1e1f7c5612d9fbdd4edbbe3b. Does that still work for you?

**Pull request merged**
